### ISSUE TITLE
make problem

### ISSUE THREAD

**Issue by loveCrypto** [FedeDP/Clightd#33] opened 2019-11-21 17:40 UTC
First thank you for this great piece of software. After a OS Update, i updated clightd and get a problem with make. Maybe you know what to do. 
 
<pre><font color="#0000EE"><b>illu</b></font>@illu <b>~/src/Clightd/build</b> <font color="#CD00CD">(</font>git<font color="#CD00CD">)</font><font color="#CDCD00">-</font><font color="#CD00CD">[</font><font color="#00CD00">master</font><font color="#CD00CD">]</font> % make
[  6%] <font color="#00CD00">Building C object CMakeFiles/clightd.dir/src/modules/backlight.c.o</font>
<b>/home/illu/src/Clightd/src/modules/backlight.c:</b> In function &apos;<b>init</b>&apos;:
<b>/home/illu/src/Clightd/src/modules/backlight.c:168:23:</b> <font color="#CD0000"><b>error: </b></font>too many arguments to function &apos;<b>map_new</b>&apos;
  168 |     running_clients = <font color="#CD0000"><b>map_new</b></font>(false, dtor_client);
      |                       <font color="#CD0000"><b>^~~~~~~</b></font>
In file included from <b>/home/illu/src/Clightd/src/modules/backlight.c:2</b>:
<b>/usr/local/include/module/map.h:26:17:</b> <font color="#00CDCD"><b>note: </b></font>declared here
   26 | _public_ map_t *<font color="#00CDCD"><b>map_new</b></font>(void);
      |                 <font color="#00CDCD"><b>^~~~~~~</b></font>
<b>/home/illu/src/Clightd/src/modules/backlight.c:</b> In function &apos;<b>add_backlight_sn</b>&apos;:
<b>/home/illu/src/Clightd/src/modules/backlight.c:260:9:</b> <font color="#CD0000"><b>error: </b></font>too few arguments to function &apos;<b>map_put</b>&apos;
  260 |         <font color="#CD0000"><b>map_put</b></font>(running_clients, sc-&gt;d.sn, sc);
      |         <font color="#CD0000"><b>^~~~~~~</b></font>
In file included from <b>/home/illu/src/Clightd/src/modules/backlight.c:2</b>:
<b>/usr/local/include/module/map.h:28:23:</b> <font color="#00CDCD"><b>note: </b></font>declared here
   28 | _public_ map_ret_code <font color="#00CDCD"><b>map_put</b></font>(map_t *m, const char *key, void *value, const bool dupkey);
      |                       <font color="#00CDCD"><b>^~~~~~~</b></font>
<b>/home/illu/src/Clightd/src/modules/backlight.c:</b> In function &apos;<b>method_setallbrightness</b>&apos;:
<b>/home/illu/src/Clightd/src/modules/backlight.c:303:9:</b> <font color="#CD00CD"><b>warning: </b></font>implicit declaration of function &apos;<b>map_clear</b>&apos; [<font color="#CD00CD"><b>-Wimplicit-function-declaration</b></font>]
  303 |         <font color="#CD00CD"><b>map_clear</b></font>(running_clients);
      |         <font color="#CD00CD"><b>^~~~~~~~~</b></font>
make[2]: *** [CMakeFiles/clightd.dir/build.make:76: CMakeFiles/clightd.dir/src/modules/backlight.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/clightd.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
</pre>

 Thx!

**Comment by FedeDP** [comment] 2019-11-22 07:39
Hi! Clightd-git and clight-git require libmodule 5.0.0 that was released a couple of months ago.
In my mind,  it wouldn't have taken so long to release new clight and clightd. Unfortunately real life is always ready to kick in, you know :)

**Comment by FedeDP** [comment] 2019-11-24 14:30
Finally i took the time to release clight and clightd 4.0. The issue is now fixed.

**Closed as completed by FedeDP** 2019-11-24 14:30 UTC
